# Site settings
title: Lise
email: elizaveta.yanovskaya@gmail.com
description: "Тыр пыр дыр"
baseurl: ""
url: "http://lise-yy.github.io/lise-io/"
twitter_username: lise_yy
github_username:  lise-yy
facebook_username:  liseyy

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
