# Site settings
title: Elizaveta Yanovskaya
email: elizaveta.yanovskaya@gmail.com
description: "A blog about web dev, management & traveling by Elizaveta Yanovskaya"
baseurl: ""
url: "http://lise.io"
twitter_username: lise_yy
github_username:  lise-yy
facebook_username:  liseyy

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
